server:
  port: 52001

spring:
  kafka:
    consumer:
      bootstrap-servers: kafka1:9092,kafka2:9093,kafka3:9094
      group-id: group-1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    dev.briiiqtt.consumer: DEBUG
    org.springframework.kafka: INFO